#!/bin/bash

# Get the forcing data
cat > ./getforc.pbs << EOF_getforc
#!/bin/bash
#PBS -m ae
#PBS -M c.carouge\@unsw.edu.au
#PBS -P w35
#PBS -q express
#PBS -l walltime=00:30:00
#PBS -l mem=100MB
#PBS -l ncpus=1
#PBS -j oe
#PBS -l wd

cd /home/561/ccc561/WRF/nu-wrf_v6-3.4.1-p1/run_lis/run_test

# get input data if first month
# else
# get the restart file and monthly input data if not first month
if [ 1 -eq 1 ]
then
    # Get python code for post-processing
    ln -sf /g/data1/w35/ccc561/LIS_WRF/coupled_testcase/decks/post-process.py .
    es=\$?
    [ \$es -ne 0 ] && exit \$es

    # Get MODEL_OUTPUT_LIST.TBL to run directory
    cp -f /g/data1/w35/ccc561/LIS_WRF/coupled_testcase/decks/./MODEL_OUTPUT_LIST.TBL_d01 /home/561/ccc561/WRF/nu-wrf_v6-3.4.1-p1/run_lis/run_test/.
    es=\$?
    [ \$es -ne 0 ] && exit \$es
else
    # Get restart file(s)
    dom=1
    while [ \$dom -le 1 ]
    do
  	ln -sf /g/data1/w35/ccc561/LIS_WRF/coupled_testcase/LIS_output/EXPTES/LIS.ETES.199806010000.d0\${dom}.CABLErst .
	es=\$?
	[ \$es -ne 0 ] && exit \$es
	dom=\$[\$dom+1]
    done
fi

# get lis.config file for this month
ln -sf /g/data1/w35/ccc561/LIS_WRF/coupled_testcase/decks/lis.config_TES_1998_06 .


# get next script
ln -sf /g/data1/w35/ccc561/LIS_WRF/coupled_testcase/decks/run_LIS_1999_06 .

exit
EOF_getforc


# Run LIS
cat > ./runLIS.pbs <<EOF_run_LIS
#!/bin/csh
#PBS -m ae
#PBS -M c.carouge\@unsw.edu.au
#PBS -P w35
#PBS -l walltime=1:20:00
#PBS -l mem=10GB
#PBS -l ncpus=64
#PBS -j oe
#PBS -q express
#PBS -l wd

module purge
module load openmpi/1.8.8
module load netcdf/4.3.3.1

# Go to the run directory
cd /home/561/ccc561/WRF/nu-wrf_v6-3.4.1-p1/run_lis/run_test/.

# Run LIS
mpirun -np \$PBS_NCPUS ./LIS -f lis.config_TES_1998_06

exit
EOF_run_LIS

# Put the results at CCRC
cat > ./putout.pbs << EOF_putout
#!/bin/csh
#PBS -m ae
#PBS -M c.carouge\@unsw.edu.au
#PBS -P w35
#PBS -q express
#PBS -l walltime=01:00:00
#PBS -l mem=2GB
#PBS -l ncpus=1
#PBS -j oe
#PBS -l wd

module load nco
module load python
module use ~access/modules
module load nccompress

cd /home/561/ccc561/WRF/nu-wrf_v6-3.4.1-p1/run_lis/run_test/
cd output/EXPTES
set dom=1
while ( \$dom <= 1 )
    mv CABLEstats.d0\${dom}.stats CABLEstats.d0\${dom}.stats.199806
    @ dom++
end

# Call python code
python /home/561/ccc561/WRF/nu-wrf_v6-3.4.1-p1/run_lis/run_test/post-process.py -s 1998 06 -e 1999 06 CABLE

# Compression
#nc_compress -o -pa -m 0 CABLE.*.nc

# Move last restart files to this level.
mv CABLE/1999/19990601/LIS.* .

# Transfer

# Remove the directory structure before copy
rm -r CABLE

#get files with rsync - if any of them fail then fail out of the pbs job
cd ../
cp -r EXPTES /g/data1/w35/ccc561/LIS_WRF/coupled_testcase/LIS_output/.
set es=\$?
[ \$es -ne 0 ] && exit \$es

# Remove last restart file if any
rm /home/561/ccc561/WRF/nu-wrf_v6-3.4.1-p1/run_lis/run_test/LIS.ETES*


#Clean OUTPUT_DIR/EXP_NAME/
rm -r EXPTES/*

# Call next script.
cd ../
./run_LIS_1999_06 >& log_1999_06

exit
EOF_putout

getjobid=`qsub getforc.pbs`
runjobid=`qsub -W depend=afterok:$getjobid runLIS.pbs`
qsub -W depend=afterok:$runjobid putout.pbs


exit
